"""At-rest encryption for personal data.

Key management (documented decision):
  * One master key, JARVIS_MASTER_KEY in .env (0600, never committed),
    generated by `jarvis keygen`. Operator backs it up off-hub.
  * Per-purpose subkeys are derived via HKDF-SHA256 ("memory", "capture",
    ...), so compromising one context doesn't hand over the others and
    purposes can be rotated independently later.
  * Symmetric encryption is Fernet (AES-128-CBC + HMAC-SHA256, versioned
    tokens) — boring, audited, and cheap on a 6 GB machine.
  * This gives field-level encryption of memory/capture content inside
    SQLite & the vector store's payloads. Full-disk encryption (LUKS) on
    the hub is recommended as the base layer underneath — see README.
"""

from __future__ import annotations

import base64

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF


def generate_master_key() -> str:
    """32 random bytes, urlsafe-base64 — suitable for JARVIS_MASTER_KEY."""
    return Fernet.generate_key().decode()


class Vault:
    def __init__(self, master_key: str):
        if not master_key:
            raise ValueError(
                "JARVIS_MASTER_KEY is not set — run `jarvis keygen` first"
            )
        try:
            self._master = base64.urlsafe_b64decode(master_key.encode())
        except Exception as exc:
            raise ValueError("JARVIS_MASTER_KEY is not valid urlsafe base64") from exc
        if len(self._master) != 32:
            raise ValueError("JARVIS_MASTER_KEY must decode to exactly 32 bytes")
        self._fernets: dict[str, Fernet] = {}

    def _fernet(self, purpose: str) -> Fernet:
        if purpose not in self._fernets:
            derived = HKDF(
                algorithm=hashes.SHA256(),
                length=32,
                salt=b"jarvis-vault-v1",
                info=purpose.encode(),
            ).derive(self._master)
            self._fernets[purpose] = Fernet(base64.urlsafe_b64encode(derived))
        return self._fernets[purpose]

    def encrypt(self, purpose: str, data: bytes | str) -> str:
        if isinstance(data, str):
            data = data.encode()
        return self._fernet(purpose).encrypt(data).decode()

    def decrypt(self, purpose: str, token: str) -> bytes:
        return self._fernet(purpose).decrypt(token.encode())

    def decrypt_text(self, purpose: str, token: str) -> str:
        return self.decrypt(purpose, token).decode()
